development:
  adapter: postgresql
  url: <%= ENV['DEV_DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
test:
  adapter: postgresql
  url: <%= ENV['TEST_DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"].presence || ENV['RAILS_MAX_THREADS'] || 5 %>
